language: node_js
node_js:
  - "10"
  - "11"
install: yarn
jobs:
  include:
    - stage: test
      script: yarn test:lint
    - stage: deploy
      script: bash ./scripts/travis-deploy.sh
cache:
  directories:
    - node_modules
