sudo: required
before_install: # if "install" is overridden
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
language: node_js
node_js:
  - "10"
  - "11"
install: yarn
jobs:
  include:
    - stage: test
      script: yarn test:lint
    - stage: deploy
      script: bash ./scripts/travis-deploy.sh
cache:
  yarn: true
  directories:
    - node_modules
